name: Publish Package to PyPI

on:
    push:
        tags:
            - "v*.*.*" # Trigger on version tags, e.g. v1.0.0

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  # Install a specific version of uv.
                  version: "0.6.4"

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: "pyproject.toml"

            - name: Build project
              run: uv build

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: dist/ # Adjust if your build output is in a different directory

    publish:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download Build Artifacts
              uses: actions/download-artifact@v3
              with:
                  name: dist

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  version: "0.6.4"

            - name: Publish to PyPi with UV
              run: uv publish

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create Github Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref }}
